In [5]:
import numpy as np
adj = np.load('./data/metr-la/adj.npz')
adj['format']

array(b'csc', dtype='|S3')

In [6]:
adj['data'].shape

(22167,)

In [16]:
import pandas as pd
data = pd.read_csv('./data/metr-la/vel.csv')
data

,64.375,67.625,67.125,61.5,66.875,68.75,65.125,67.125.1,59.625,62.75,...,45.625,65.5.2,64.5.4,66.42857142857143,66.875.7,59.375,69.0.1,59.25,69.0.2,61.875
0,62.666667,68.555556,65.444444,62.444444,64.444444,68.111111,65.000000,65.000000,57.444444,63.333333,...,50.666667,69.875000,66.666667,58.555556,62.000000,61.111111,64.444444,55.888889,68.444444,62.875000
1,64.000000,63.750000,60.000000,59.000000,66.500000,66.250000,64.500000,64.250000,63.875000,65.375000,...,44.125000,69.000000,56.500000,59.250000,68.125000,62.500000,65.625000,61.375000,69.857143,62.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,57.333333,69.000000,67.666667,61.666667,67.333333,69.000000,60.666667,67.333333,63.000000,63.333333,...,42.000000,70.000000,68.333333,57.333333,66.000000,54.666667,64.666667,57.666667,69.000000,57.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34266,65.000000,65.888889,68.555556,61.666667,0.000000,54.555556,62.444444,63.333333,59.222222,65.333333,...,52.888889,69.000000,65.111111,55.666667,66.333333,62.444444,66.777778,64.888889,69.666667,62.333333
34267,61.375000,65.625000,66.500000,62.750000,0.000000,50.500000,62.000000,67.000000,65.250000,67.125000,...,54.000000,69.250000,60.125000,60.500000,67.250000,59.375000,66.000000,61.250000,69.000000,62.000000
34268,67.000000,59.666667,69.555556,61.000000,0.000000,44.777778,64.222222,63.777778,59.777778,57.666667,...,51.333333,67.888889,64.333333,57.000000,66.000000,62.666667,68.666667,63.333333,67.444444,61.222222
34269,66.750000,62.250000,66.000000,59.625000,0.000000,53.000000,64.285714,64.125000,60.875000,66.250000,...,51.125000,69.375000,61.625000,60.500000,65.625000,66.375000,69.500000,63.000000,67.875000,63.500000
34270,65.111111,66.888889,66.777778,61.222222,0.000000,49.555556,65.777778,65.111111,63.000000,61.666667,...,56.000000,67.444444,64.888889,60.888889,64.222222,66.444444,68.444444,63.555556,68.666667,61.777778

In [4]:
import scipy.sparse as sp 

adj = sp.load_npz('./data/metr-la/adj.npz')
adj = adj.tocsc()
adj

<207x207 sparse matrix of type '<class 'numpy.float64'>'
	with 22167 stored elements in Compressed Sparse Column format>